{
  "seleniumLog": [],
  "checkPoints": [
    {
      "message": "An unknown server-side error occurred while processing the command. Original error: Could not find package com.android.calculator2 on the device\nBuild info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'\nSystem info: host: 'AHMEDRAGAB', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1'\nDriver info: driver.version: RemoteWebDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find package com.android.calculator2 on the device\n    at getResponseForW3CError (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:800:13)\n    at asyncHandler$ (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:352:37)\n    at tryCatch (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\node_modules\\babel-runtime\\regenerator\\runtime.js:67:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\node_modules\\babel-runtime\\regenerator\\runtime.js:315:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\node_modules\\babel-runtime\\regenerator\\runtime.js:100:21)\n    at GeneratorFunctionPrototype.invoke (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\node_modules\\babel-runtime\\regenerator\\runtime.js:136:37)\n    at <anonymous>",
      "type": "Fail",
      "screenshot": "",
      "duration": 0,
      "threshold": 0,
      "subCheckPoints": []
    }
  ],
  "errorTrace": "org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find package com.android.calculator2 on the device\nBuild info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'\nSystem info: host: 'AHMEDRAGAB', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1'\nDriver info: driver.version: RemoteWebDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find package com.android.calculator2 on the device\n    at getResponseForW3CError (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:800:13)\n    at asyncHandler$ (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:352:37)\n    at tryCatch (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\node_modules\\babel-runtime\\regenerator\\runtime.js:67:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\node_modules\\babel-runtime\\regenerator\\runtime.js:315:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\node_modules\\babel-runtime\\regenerator\\runtime.js:100:21)\n    at GeneratorFunctionPrototype.invoke (C:\\Users\\a.ragab\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-base-driver\\node_modules\\babel-runtime\\regenerator\\runtime.js:136:37)\n    at <anonymous>\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\r\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)\r\n\tat org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)\r\n\tat org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)\r\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)\r\n\tat java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)\r\n\tat java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)\r\n\tat java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)\r\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)\r\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)\r\n\tat java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)\r\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r\n\tat java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)\r\n\tat org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:145)\r\n\tat test.calc.setUp(calc.java:33)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)\r\n\tat org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)\r\n\tat org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)\r\n\tat org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)\r\n\tat org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:781)\r\n\tat org.testng.TestRunner.run(TestRunner.java:635)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:387)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:289)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1133)\r\n\tat org.testng.TestNG.run(TestNG.java:1104)\r\n\tat org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)\r\n\tat org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)\r\n"
}